default_platform(:ios)
fastlane_version('2.94.0')
ensure_xcode_version(version: '9.3')

platform :ios do
  before_all do
    ensure_git_status_clean
  end

  after_all do
    clean_build_artifacts
    reset_git_repo(
      force: true,
      skip_clean: true
    )
  end

  desc 'Build and deploy to TestFlight for Beta Testing'
  lane :beta do
    carthage(
      platform: 'iOS',
      cache_builds: true
    )
    match
    automatic_code_signing(
      use_automatic_signing: false,
      profile_name: ENV['sigh_com.guidolim.Dron_appstore_profile-name'],
      team_id: 'JW682CU4GW',
      code_sign_identity: 'iPhone Distribution'
    )
    version_number = get_version_number
    increment_build_number(
      build_number: latest_testflight_build_number(version: version_number) + 1
    )
    add_badge(
      shield: "Build-#{get_build_number}-orange",
      glob: '/Dron/**/*.appiconset/*.{png,PNG}'
    )
    gym
    pilot(
      distribute_external: true,
      notify_external_testers: true,
      groups: ['ios-beta-external'],
      changelog: 'This is an automated build, so there is no "What to Test". '\
                  'Just play around and let me know if you find any issue.'
    )
    download_dsyms(
      version: version_number,
      build_number: get_build_number
    )
    upload_symbols_to_crashlytics(
      binary_path: './Scripts/upload-symbols',
      dsym_worker_threads: 15
    )
  end
end
