default_platform(:ios)

platform :ios do
  desc 'Build and deploy to Crashlytics Beta'
  lane :alpha do
    carthage(
      platform: 'iOS',
      cache_builds: true
    )
    cert
    sigh
    increment_build_number(
      build_number: ENV['BITRISE_BUILD_NUMBER']
    )
    add_badge(
      alpha: true,
      shield: "#{get_version_number}-#{get_build_number}-orange",
      shield_io_timeout: 60
    )
    gym
    crashlytics(
      groups: 'ios-beta'
    )
  end
end
